name: Setup Node.js and pnpm
description: Install pnpm, Node.js, and project dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.13.1
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      shell: bash
