packages:
  - 'packages/*'
  - 'examples/*'
catalog:
  # runtime
  "@types/node": 22.15.30
  "typescript": ^5.8.2
  # google cloud
  "@firebase/app": ^0.13.1
  "@firebase/firestore": ^4.7.17
  "@google-cloud/firestore": ^7.11.1
  # linter / formatter
  "@biomejs/biome": ^1.9.4
  # testing
  "vitest": ^3.2.3
  "@vitest/coverage-v8": ^3.2.3
  "vite-tsconfig-paths": ^5.1.4
  "testcontainers": ^11.0.2
