packages:
  - 'packages/*'
  - 'examples/*'
catalog:
  "@firebase/app": ^0.11.3
  "@firebase/firestore": ^4.7.9
  "@google-cloud/firestore": ^7.11.0
  "@types/node": 22.13.10
  "@biomejs/biome": ^1.9.4
  "@vitest/coverage-v8": ^2.1.6
  "testcontainers": ^10.20.0
  "typescript": ^5.8.2
  "vite-tsconfig-paths": ^5.1.4
  "vitest": ^2.1.6
