packages:
  - 'packages/*'
  - 'examples/*'
catalog:
  # runtime
  "@types/node": 25.0.2
  "typescript": ^5.9.3
  # google cloud
  "@firebase/app": ^0.14.6
  "@firebase/firestore": ^4.9.2
  "@google-cloud/firestore": ^8.0.0
  # linter / formatter
  "@biomejs/biome": ^2.3.9
  # testing
  "vitest": ^4.0.15
  "@vitest/coverage-v8": ^4.0.15
  "vite-tsconfig-paths": ^6.0.1
  "testcontainers": ^11.10.0
