packages:
  - 'packages/*'
  - 'examples/*'
catalog:
  # runtime
  "@types/node": 20.0.0
  "typescript": ^5.8.2
  # google cloud
  "@firebase/app": ^0.12.3
  "@firebase/firestore": ^4.7.14
  "@google-cloud/firestore": ^7.11.1
  # linter / formatter
  "@biomejs/biome": ^1.9.4
  # testing
  "vitest": ^3.2.0
  "@vitest/coverage-v8": ^3.2.0
  "vite-tsconfig-paths": ^5.1.4
  "testcontainers": ^10.26.0
